"""add_category_image_url_and_desc

Revision ID: 704695356f75
Revises: 
Create Date: 2026-03-10 18:50:47.827272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '704695356f75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    cols = [c.get('name') for c in inspector.get_columns('categories')]

    if 'description' not in cols:
        op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    if 'image_url' not in cols:
        op.add_column('categories', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image_url')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
