"""update_product_size_pricing

Revision ID: 9719d80e4845
Revises: 95e599627fdb
Create Date: 2026-03-16 03:02:59.534851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9719d80e4845'
down_revision: Union[str, Sequence[str], None] = '95e599627fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sizes', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('product_sizes', sa.Column('discount_price', sa.Float(), nullable=True))
    op.drop_column('product_sizes', 'additional_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sizes', sa.Column('additional_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('product_sizes', 'discount_price')
    op.drop_column('product_sizes', 'price')
    # ### end Alembic commands ###
